
title: Curriculum Vitae- Abigael Saruni
email: abbynaila26@gmail.com
description: "Electrical & Computer Engineering Student | Cybersecurity & AI Enthusiast"
twitter_username: nylah_abbie
github_username: s-nailantei
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)

author:
  name: "Abigael Saruni"
  avatar: "/assets/images/My_Photo.jpg"
  bio: "Electrical & Computer Engineering student with a passion for AI, cybersecurity, and embedded systems.."
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/abigael-saruni-a26787356"
    - label: "Twitter"
      url: "https://x.com/nylah_abbie"
    - label: "GitHub"
      url: "https://github.com/s-nailantei"

footer:
  links:
    - label: "Twitter"
      url: "https://x.com/nylah_abbie"
    - label: "GitHub"
      url: "https://github.com/s-nailantei"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
