
title: Abigael Saruni | Electrical & Computer Engineer
url: "https://nailantei.github.io" 
baseurl: ""
email: abbynaila26@gmail.com
description: "Electrical & Computer Engineering Student | Cybersecurity & AI Specialist | Embedded Systems Developer"
keywords: "cybersecurity, machine learning, embedded systems, AI, data science"


author:
  name: "Abigael Saruni"
  avatar: "https://nailantei.github.io/assets/images/My_Photo.jpg"
  bio: "Electrical & Computer Engineering student specializing in AI applications for cybersecurity systems. Passionate about secure embedded systems development and machine learning."
  location: "Nairobi, Kenya"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/abigael-saruni-a26787356"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/s-nailantei"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Abigael-Saruni" 
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:abbynaila26@gmail.com"


markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


minimal_mistakes_skin: "neon" 
search: true
read_time: true
words_per_minute: 180
show_author_profile: true


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true

# Content Organization
collections:
  projects:
    output: true
    permalink: /projects/:path/
  labs:
    output: true
    permalink: /labs/:path/


seo:
  type: Person
  links:
    - "https://github.com/s-nailantei"
    - "https://linkedin.com/in/abigael-saruni-a26787356"

# Footer
footer:
  copyright: "&copy; 2023 Abigael Saruni. All rights reserved."
  links:
    - label: "Privacy Policy"
      url: "/privacy/"
    - label: "GitHub"
      url: "https://github.com/s-nailantei"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/abigael-saruni-a26787356"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - .vscode
